name: PlatformIO CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run setup
        run: pwd

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build PlatformIO project
        run: |
          cd "Software/Source_code"
          pio run
          mkdir -p output
          mv build output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: platformio-build
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: platformio-build
          path: Software/Sourse_code/build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."

